// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tablApi.Data;

#nullable disable

namespace tablApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250528055108_v3update")]
    partial class v3update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tablApi.Data.ClassList", b =>
                {
                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.Property<int>("Class_ID")
                        .HasColumnType("int");

                    b.HasKey("Student_ID", "Class_ID");

                    b.HasIndex("Class_ID");

                    b.ToTable("ClassLists");

                    b.HasData(
                        new
                        {
                            Student_ID = 1,
                            Class_ID = 1
                        },
                        new
                        {
                            Student_ID = 1,
                            Class_ID = 2
                        },
                        new
                        {
                            Student_ID = 1,
                            Class_ID = 3
                        },
                        new
                        {
                            Student_ID = 1,
                            Class_ID = 5
                        },
                        new
                        {
                            Student_ID = 2,
                            Class_ID = 1
                        },
                        new
                        {
                            Student_ID = 2,
                            Class_ID = 3
                        },
                        new
                        {
                            Student_ID = 2,
                            Class_ID = 4
                        },
                        new
                        {
                            Student_ID = 2,
                            Class_ID = 5
                        });
                });

            modelBuilder.Entity("tablApi.Data.StudentClassEntry", b =>
                {
                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.Property<int>("ClassEntry_ID")
                        .HasColumnType("int");

                    b.HasKey("Student_ID", "ClassEntry_ID");

                    b.HasIndex("ClassEntry_ID");

                    b.ToTable("StudentClassEntries");

                    b.HasData(
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 1
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 1
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 2
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 2
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 3
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 3
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 4
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 4
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 5
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 5
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 6
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 6
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 7
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 7
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 8
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 8
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 9
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 9
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 10
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 10
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 11
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 11
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 12
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 12
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 13
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 13
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 14
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 14
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 15
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 15
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 16
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 16
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 17
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 17
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 18
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 18
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 19
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 19
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 20
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 20
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 21
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 21
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 22
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 22
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 23
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 23
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 24
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 24
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 25
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 25
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 26
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 26
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 27
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 27
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 28
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 29
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 30
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 31
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 32
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 33
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 34
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 35
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 36
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 37
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 38
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 39
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 40
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 41
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 42
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 43
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 44
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 45
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 46
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 47
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 48
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 49
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 50
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 51
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 52
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 53
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 54
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 55
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 55
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 56
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 56
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 57
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 57
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 58
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 58
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 59
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 59
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 60
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 60
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 61
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 61
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 62
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 62
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 63
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 63
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 64
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 64
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 65
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 65
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 66
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 66
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 67
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 67
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 68
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 68
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 69
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 69
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 70
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 70
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 71
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 71
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 72
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 72
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 73
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 73
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 74
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 74
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 75
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 75
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 76
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 76
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 77
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 77
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 78
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 78
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 79
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 79
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 80
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 80
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 81
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 81
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 82
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 83
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 84
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 85
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 86
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 87
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 88
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 89
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 90
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 91
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 92
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 93
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 94
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 95
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 96
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 97
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 98
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 99
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 100
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 101
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 102
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 103
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 104
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 105
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 106
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 107
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 108
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 109
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 109
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 110
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 110
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 111
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 111
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 112
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 112
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 113
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 113
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 114
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 114
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 115
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 115
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 116
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 116
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 117
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 117
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 118
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 118
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 119
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 119
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 120
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 120
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 121
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 121
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 122
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 122
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 123
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 123
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 124
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 124
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 125
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 125
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 126
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 126
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 127
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 127
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 128
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 128
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 129
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 129
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 130
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 130
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 131
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 131
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 132
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 132
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 133
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 133
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 134
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 134
                        },
                        new
                        {
                            Student_ID = 1,
                            ClassEntry_ID = 135
                        },
                        new
                        {
                            Student_ID = 2,
                            ClassEntry_ID = 135
                        });
                });

            modelBuilder.Entity("tablApi.Model.Class", b =>
                {
                    b.Property<int>("Class_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Class_ID"));

                    b.Property<string>("Class_Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tutor_ID")
                        .HasColumnType("int");

                    b.HasKey("Class_ID");

                    b.HasIndex("Tutor_ID");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Class_ID = 1,
                            Class_Desc = "Introduction to Basic Mathematics",
                            Class_Name = "Mathematics 101",
                            EndDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Room = "Room 101",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tutor_ID = 1
                        },
                        new
                        {
                            Class_ID = 2,
                            Class_Desc = "Introduction to Physics",
                            Class_Name = "Physics 101",
                            EndDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Room = "Room 102",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tutor_ID = 2
                        },
                        new
                        {
                            Class_ID = 3,
                            Class_Desc = "Introduction to Chemistry",
                            Class_Name = "Chemistry 101",
                            EndDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Room = "Room 103",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tutor_ID = 1
                        },
                        new
                        {
                            Class_ID = 4,
                            Class_Desc = "Introduction to Biology",
                            Class_Name = "Biology 101",
                            EndDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Room = "Room 104",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tutor_ID = 2
                        },
                        new
                        {
                            Class_ID = 5,
                            Class_Desc = "Introduction to Programming",
                            Class_Name = "Computer Science 101",
                            EndDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Room = "Room 105",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tutor_ID = 1
                        });
                });

            modelBuilder.Entity("tablApi.Model.ClassEntry", b =>
                {
                    b.Property<int>("ClassEntry_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassEntry_ID"));

                    b.Property<int>("ClassSchedule_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ClassEntry_ID");

                    b.HasIndex("ClassSchedule_ID");

                    b.ToTable("ClassEntries");

                    b.HasData(
                        new
                        {
                            ClassEntry_ID = 1,
                            ClassSchedule_ID = 1,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 2,
                            ClassSchedule_ID = 1,
                            Date = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 3,
                            ClassSchedule_ID = 1,
                            Date = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 4,
                            ClassSchedule_ID = 1,
                            Date = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 5,
                            ClassSchedule_ID = 1,
                            Date = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 6,
                            ClassSchedule_ID = 1,
                            Date = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 7,
                            ClassSchedule_ID = 1,
                            Date = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 8,
                            ClassSchedule_ID = 1,
                            Date = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 9,
                            ClassSchedule_ID = 1,
                            Date = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 10,
                            ClassSchedule_ID = 1,
                            Date = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 11,
                            ClassSchedule_ID = 1,
                            Date = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 12,
                            ClassSchedule_ID = 1,
                            Date = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 13,
                            ClassSchedule_ID = 1,
                            Date = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 14,
                            ClassSchedule_ID = 1,
                            Date = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 15,
                            ClassSchedule_ID = 2,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 16,
                            ClassSchedule_ID = 2,
                            Date = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 17,
                            ClassSchedule_ID = 2,
                            Date = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 18,
                            ClassSchedule_ID = 2,
                            Date = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 19,
                            ClassSchedule_ID = 2,
                            Date = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 20,
                            ClassSchedule_ID = 2,
                            Date = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 21,
                            ClassSchedule_ID = 2,
                            Date = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 22,
                            ClassSchedule_ID = 2,
                            Date = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 23,
                            ClassSchedule_ID = 2,
                            Date = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 24,
                            ClassSchedule_ID = 2,
                            Date = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 25,
                            ClassSchedule_ID = 2,
                            Date = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 26,
                            ClassSchedule_ID = 2,
                            Date = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 27,
                            ClassSchedule_ID = 2,
                            Date = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 28,
                            ClassSchedule_ID = 3,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 29,
                            ClassSchedule_ID = 3,
                            Date = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 30,
                            ClassSchedule_ID = 3,
                            Date = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 31,
                            ClassSchedule_ID = 3,
                            Date = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 32,
                            ClassSchedule_ID = 3,
                            Date = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 33,
                            ClassSchedule_ID = 3,
                            Date = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 34,
                            ClassSchedule_ID = 3,
                            Date = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 35,
                            ClassSchedule_ID = 3,
                            Date = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 36,
                            ClassSchedule_ID = 3,
                            Date = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 37,
                            ClassSchedule_ID = 3,
                            Date = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 38,
                            ClassSchedule_ID = 3,
                            Date = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 39,
                            ClassSchedule_ID = 3,
                            Date = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 40,
                            ClassSchedule_ID = 3,
                            Date = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 41,
                            ClassSchedule_ID = 3,
                            Date = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 42,
                            ClassSchedule_ID = 4,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 43,
                            ClassSchedule_ID = 4,
                            Date = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 44,
                            ClassSchedule_ID = 4,
                            Date = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 45,
                            ClassSchedule_ID = 4,
                            Date = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 46,
                            ClassSchedule_ID = 4,
                            Date = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 47,
                            ClassSchedule_ID = 4,
                            Date = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 48,
                            ClassSchedule_ID = 4,
                            Date = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 49,
                            ClassSchedule_ID = 4,
                            Date = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 50,
                            ClassSchedule_ID = 4,
                            Date = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 51,
                            ClassSchedule_ID = 4,
                            Date = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 52,
                            ClassSchedule_ID = 4,
                            Date = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 53,
                            ClassSchedule_ID = 4,
                            Date = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 54,
                            ClassSchedule_ID = 4,
                            Date = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 55,
                            ClassSchedule_ID = 5,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 56,
                            ClassSchedule_ID = 5,
                            Date = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 57,
                            ClassSchedule_ID = 5,
                            Date = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 58,
                            ClassSchedule_ID = 5,
                            Date = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 59,
                            ClassSchedule_ID = 5,
                            Date = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 60,
                            ClassSchedule_ID = 5,
                            Date = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 61,
                            ClassSchedule_ID = 5,
                            Date = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 62,
                            ClassSchedule_ID = 5,
                            Date = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 63,
                            ClassSchedule_ID = 5,
                            Date = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 64,
                            ClassSchedule_ID = 5,
                            Date = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 65,
                            ClassSchedule_ID = 5,
                            Date = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 66,
                            ClassSchedule_ID = 5,
                            Date = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 67,
                            ClassSchedule_ID = 5,
                            Date = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 68,
                            ClassSchedule_ID = 5,
                            Date = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 69,
                            ClassSchedule_ID = 6,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 70,
                            ClassSchedule_ID = 6,
                            Date = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 71,
                            ClassSchedule_ID = 6,
                            Date = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 72,
                            ClassSchedule_ID = 6,
                            Date = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 73,
                            ClassSchedule_ID = 6,
                            Date = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 74,
                            ClassSchedule_ID = 6,
                            Date = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 75,
                            ClassSchedule_ID = 6,
                            Date = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 76,
                            ClassSchedule_ID = 6,
                            Date = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 77,
                            ClassSchedule_ID = 6,
                            Date = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 78,
                            ClassSchedule_ID = 6,
                            Date = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 79,
                            ClassSchedule_ID = 6,
                            Date = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 80,
                            ClassSchedule_ID = 6,
                            Date = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 81,
                            ClassSchedule_ID = 6,
                            Date = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 82,
                            ClassSchedule_ID = 7,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 83,
                            ClassSchedule_ID = 7,
                            Date = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 84,
                            ClassSchedule_ID = 7,
                            Date = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 85,
                            ClassSchedule_ID = 7,
                            Date = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 86,
                            ClassSchedule_ID = 7,
                            Date = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 87,
                            ClassSchedule_ID = 7,
                            Date = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 88,
                            ClassSchedule_ID = 7,
                            Date = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 89,
                            ClassSchedule_ID = 7,
                            Date = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 90,
                            ClassSchedule_ID = 7,
                            Date = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 91,
                            ClassSchedule_ID = 7,
                            Date = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 92,
                            ClassSchedule_ID = 7,
                            Date = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 93,
                            ClassSchedule_ID = 7,
                            Date = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 94,
                            ClassSchedule_ID = 7,
                            Date = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 95,
                            ClassSchedule_ID = 7,
                            Date = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 96,
                            ClassSchedule_ID = 8,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 97,
                            ClassSchedule_ID = 8,
                            Date = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 98,
                            ClassSchedule_ID = 8,
                            Date = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 99,
                            ClassSchedule_ID = 8,
                            Date = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 100,
                            ClassSchedule_ID = 8,
                            Date = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 101,
                            ClassSchedule_ID = 8,
                            Date = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 102,
                            ClassSchedule_ID = 8,
                            Date = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 103,
                            ClassSchedule_ID = 8,
                            Date = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 104,
                            ClassSchedule_ID = 8,
                            Date = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 105,
                            ClassSchedule_ID = 8,
                            Date = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 106,
                            ClassSchedule_ID = 8,
                            Date = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 107,
                            ClassSchedule_ID = 8,
                            Date = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 108,
                            ClassSchedule_ID = 8,
                            Date = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 109,
                            ClassSchedule_ID = 9,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 110,
                            ClassSchedule_ID = 9,
                            Date = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 111,
                            ClassSchedule_ID = 9,
                            Date = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 112,
                            ClassSchedule_ID = 9,
                            Date = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 113,
                            ClassSchedule_ID = 9,
                            Date = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 114,
                            ClassSchedule_ID = 9,
                            Date = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 115,
                            ClassSchedule_ID = 9,
                            Date = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 116,
                            ClassSchedule_ID = 9,
                            Date = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 117,
                            ClassSchedule_ID = 9,
                            Date = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 118,
                            ClassSchedule_ID = 9,
                            Date = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 119,
                            ClassSchedule_ID = 9,
                            Date = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 120,
                            ClassSchedule_ID = 9,
                            Date = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 121,
                            ClassSchedule_ID = 9,
                            Date = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 122,
                            ClassSchedule_ID = 9,
                            Date = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 123,
                            ClassSchedule_ID = 10,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 124,
                            ClassSchedule_ID = 10,
                            Date = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 125,
                            ClassSchedule_ID = 10,
                            Date = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 126,
                            ClassSchedule_ID = 10,
                            Date = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 127,
                            ClassSchedule_ID = 10,
                            Date = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 128,
                            ClassSchedule_ID = 10,
                            Date = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 129,
                            ClassSchedule_ID = 10,
                            Date = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 130,
                            ClassSchedule_ID = 10,
                            Date = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 131,
                            ClassSchedule_ID = 10,
                            Date = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 132,
                            ClassSchedule_ID = 10,
                            Date = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 133,
                            ClassSchedule_ID = 10,
                            Date = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 134,
                            ClassSchedule_ID = 10,
                            Date = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClassEntry_ID = 135,
                            ClassSchedule_ID = 10,
                            Date = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("tablApi.Model.ClassSchedule", b =>
                {
                    b.Property<int>("Schedule_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Schedule_ID"));

                    b.Property<int>("Class_ID")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Schedule_ID");

                    b.HasIndex("Class_ID");

                    b.ToTable("ClassSchedules");

                    b.HasData(
                        new
                        {
                            Schedule_ID = 1,
                            Class_ID = 1,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Schedule_ID = 2,
                            Class_ID = 1,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Schedule_ID = 3,
                            Class_ID = 2,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Schedule_ID = 4,
                            Class_ID = 2,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Schedule_ID = 5,
                            Class_ID = 3,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Schedule_ID = 6,
                            Class_ID = 3,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Schedule_ID = 7,
                            Class_ID = 4,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Schedule_ID = 8,
                            Class_ID = 4,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Schedule_ID = 9,
                            Class_ID = 5,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Schedule_ID = 10,
                            Class_ID = 5,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("tablApi.Model.Student", b =>
                {
                    b.Property<int>("Student_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Student_ID"));

                    b.Property<string>("Student_LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Student_ID");

                    b.HasIndex("User_ID")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Student_ID = 1,
                            Student_LastName = "Johnson",
                            Student_firstName = "Alice",
                            User_ID = 4
                        },
                        new
                        {
                            Student_ID = 2,
                            Student_LastName = "Williams",
                            Student_firstName = "Bob",
                            User_ID = 5
                        });
                });

            modelBuilder.Entity("tablApi.Model.Tutor", b =>
                {
                    b.Property<int>("Tutor_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tutor_ID"));

                    b.Property<string>("Tutor_LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tutor_firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Tutor_ID");

                    b.HasIndex("User_ID")
                        .IsUnique();

                    b.ToTable("Tutors");

                    b.HasData(
                        new
                        {
                            Tutor_ID = 1,
                            Tutor_LastName = "Smith",
                            Tutor_firstName = "John",
                            User_ID = 2
                        },
                        new
                        {
                            Tutor_ID = 2,
                            Tutor_LastName = "Doe",
                            Tutor_firstName = "Jane",
                            User_ID = 3
                        });
                });

            modelBuilder.Entity("tablApi.Model.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<string>("User_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            User_ID = 1,
                            User_email = "admin",
                            User_password = "admin",
                            User_type = "Admin"
                        },
                        new
                        {
                            User_ID = 2,
                            User_email = "john.tutor@school.com",
                            User_password = "tutor123",
                            User_type = "Tutor"
                        },
                        new
                        {
                            User_ID = 3,
                            User_email = "jane.tutor@school.com",
                            User_password = "tutor123",
                            User_type = "Tutor"
                        },
                        new
                        {
                            User_ID = 4,
                            User_email = "alice.student@school.com",
                            User_password = "student123",
                            User_type = "Student"
                        },
                        new
                        {
                            User_ID = 5,
                            User_email = "bob.student@school.com",
                            User_password = "student123",
                            User_type = "Student"
                        });
                });

            modelBuilder.Entity("tablApi.Data.ClassList", b =>
                {
                    b.HasOne("tablApi.Model.Class", "Class")
                        .WithMany()
                        .HasForeignKey("Class_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tablApi.Model.Student", "Student")
                        .WithMany()
                        .HasForeignKey("Student_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("tablApi.Data.StudentClassEntry", b =>
                {
                    b.HasOne("tablApi.Model.ClassEntry", "ClassEntry")
                        .WithMany()
                        .HasForeignKey("ClassEntry_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tablApi.Model.Student", "Student")
                        .WithMany()
                        .HasForeignKey("Student_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassEntry");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("tablApi.Model.Class", b =>
                {
                    b.HasOne("tablApi.Model.Tutor", "Tutor")
                        .WithMany("Classes")
                        .HasForeignKey("Tutor_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("tablApi.Model.ClassEntry", b =>
                {
                    b.HasOne("tablApi.Model.ClassSchedule", "ClassSchedule")
                        .WithMany("ClassEntries")
                        .HasForeignKey("ClassSchedule_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSchedule");
                });

            modelBuilder.Entity("tablApi.Model.ClassSchedule", b =>
                {
                    b.HasOne("tablApi.Model.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("Class_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("tablApi.Model.Student", b =>
                {
                    b.HasOne("tablApi.Model.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("tablApi.Model.Student", "User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("tablApi.Model.Tutor", b =>
                {
                    b.HasOne("tablApi.Model.User", "User")
                        .WithOne("Tutor")
                        .HasForeignKey("tablApi.Model.Tutor", "User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("tablApi.Model.Class", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("tablApi.Model.ClassSchedule", b =>
                {
                    b.Navigation("ClassEntries");
                });

            modelBuilder.Entity("tablApi.Model.Tutor", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("tablApi.Model.User", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Tutor");
                });
#pragma warning restore 612, 618
        }
    }
}
